### ISSUE TITLE
Update/remove old non-LFS branches

### ISSUE THREAD

**Issue by NiklasRosenstein** [project-unik/horror-survival#1]
The `pathfinding`, `savesystem` and `savesystem1` branches don't use Git LFS. Can we do the same squash we did on the master, or can the changes already be integrated? In the latter case, they should not be merged directly but manually to make sure the assets are managed by LFS.

**Comment by lukasstevens** [comment]
Those branches are essentially obsolete. I think we can also delete them.

**Comment by kappelmann** [comment]
Deleted.
